version: 2
jobs:
  build:
    docker:
      - image: whill/clang-gtest:0.0.1
      
    working_directory: ~/circleci-clang

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "b6:5a:9b:5f:d6:3e:68:64:5a:4e:81:01:d6:69:6a:08"

      # run tests!
      - run:
          name: run tests
          command: |
            chmod a+x build.sh
            ./build.sh
      
      - run:
          name: Chat Notification Success
          when: on_success
          command: >
            curl --header "Content-Type: application/json" 
            --request POST 
            --data "{\"cards\":[{\"header\":{\"title\":\"Build ${CIRCLE_BUILD_NUM} passed.\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170510/success_404253.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"${CIRCLE_SHA1}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}}]}]}]}]}"
            ${CHAT_WEBHOOK_URL}

      - run:
          name: Chat Notification Fail
          when: on_fail
          command: >
            curl --header "Content-Type: application/json" 
            --request POST 
            --data "{\"cards\":[{\"header\":{\"title\":\"Oops. Build ${CIRCLE_BUILD_NUM} failed.\",\"subtitle\":\"${CIRCLE_PROJECT_REPONAME}\",\"imageUrl\":\"https://png.pngtree.com/svg/20170406/icon_failed__1325447.png\",\"imageStyle\":\"IMAGE\"},\"sections\":[{\"widgets\":[{\"keyValue\":{\"topLabel\":\"${CIRCLE_TAG}\",\"content\":\"${CIRCLE_SHA1}\"}}]},{\"widgets\":[{\"buttons\":[{\"textButton\":{\"text\":\"DETAILS\",\"onClick\":{\"openLink\":{\"url\":\"${CIRCLE_BUILD_URL}\"}}}}]}]}]}]}"
            ${CHAT_WEBHOOK_URL}

      - store_test_results:
          path: test-results
