version: 2
jobs:
  build:
    docker:
      - image: chronushadow/clang:bionic
      
    working_directory: ~/circleci-clang

    steps:
      - checkout
        
      # run tests!
      - run:
          name: run tests
          command: |
            chmod a+x build.sh
            ./build.sh
          